# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, style, refactor, test, chore, ci, perf, build, revert]
-   repo: https://github.com/astral-sh/ruff-pre-commit.git
    rev: v0.12.5
    hooks:
      - id: ruff
        args: [ "--fix" ]
      - id: ruff-format
-   repo: local
    hooks:
      - id: mypy
        name: mypy
        # Use system language to leverage pyproject.toml dependencies instead of duplicating them
        language: system
        entry: mypy src tests
        types: [python]
        pass_filenames: false
        always_run: true
-   repo: https://github.com/rstcheck/rstcheck
    rev: v6.2.5
    hooks:
      - id: rstcheck
        args: ["--ignore-directives=automodule,click", "--report-level=WARNING"]
        additional_dependencies:
          - sphinx==7.2.6
          - toml==0.10.2
-   repo: local
    hooks:
      # - id: pylint-sort
      #   name: pylint sort check
      #   language: system
      #   entry: pylint --disable=all --enable=unsorted-functions,unsorted-methods
      #   types: [python]
      #   pass_filenames: true
      #   # Don't fail on sorting issues for now, just warn
      #   verbose: true
      - id: coverage
        name: coverage
        language: system
        entry: ./scripts/run-coverage.sh
        always_run: true
        pass_filenames: false
      - id: coverage-report
        name: coverage report
        language: system
        entry: python -m coverage report -m
        always_run: true
        pass_filenames: false
