# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/astral-sh/ruff-pre-commit.git
    rev: v0.12.5
    hooks:
      - id: ruff
        args: [ "--fix" ]
      - id: ruff-format
-   repo: local
    hooks:
      - id: mypy
        name: mypy
        # Use system language to leverage pyproject.toml dependencies instead of duplicating them
        language: system
        entry: mypy src tests
        types: [python]
        pass_filenames: false
        always_run: true
-   repo: https://github.com/rstcheck/rstcheck
    rev: v6.2.5
    hooks:
      - id: rstcheck
        args: ["--ignore-directives=automodule,click", "--report-level=WARNING"]
        additional_dependencies:
          - sphinx==7.2.6
          - toml==0.10.2
-   repo: local
    hooks:
      - id: coverage
        name: coverage
        language: system
        entry: python -m coverage run -m pytest tests
        always_run: true
        pass_filenames: false
      - id: coverage-report
        name: coverage report
        language: system
        entry: python -m coverage report -m
        always_run: true
        pass_filenames: false
